<?php
    
    require_once 'views/layaout/header.php';
 ?>
<div class="container">
    <br><br><br>
    <div class="row">
    <h1>Añadir nueva Explotación</h1>
    </div>
    <br>
    <div class="row">
        <form action="<?php echo base_url . "sadmin.php/?controller=Explotacion&action=add"; ?>" method="POST" class="col">
            <div class="form-group">
                <label for="id">Introduzca ID</label>
                <input class="form-control" type="text" name="id_explotacion" id="id_explotacion" required>
            </div>
            <div class="form-group">
                <label for="id">Introduzca Municipio</label>
                <input class="form-control" type="text" name="municipio" id="municipio" required>
            </div>
            <br><br>
            <button type="submit" class="btn btn-success">Añadir</button>
        </form>
    </div>
</div>    
<?php  require_once 'views/layaout/footer.php';   ?>