<?php
    
    require_once 'views/layaout/header.php';
 ?>
<div class="container">
    <br><br><br>
    <div class="row">
    <h1>Añadir nueva Explotación</h1>
    </div>
    <br>
    <div class="row">
        <form action="#" class="col">
            <div class="form-group">
                <label for="id">Introduzca ID</label>
                <input class="form-control" type="text" name="id_explotacion" id="id_explotacion">
            </div>
            <div class="form-group">
                <label for="id">Introduzca Municipio</label>
                <input class="form-control" type="text" name="municipio" id="municipio">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>    
<?php  require_once 'views/layaout/footer.php';   ?>