<?php
    $menu = [
      "inicio"        =>  "",
      "explotaciones" =>  "active",
      "acceso"        =>  "",
      "registro"      =>  ""
    ];
    $id = (isset($consulta))? $consulta['id_explotacion'] : "";
    $municipio = (isset($consulta))? $consulta['municipio'] : "";
        
    require_once 'views/layaout/header.php';
 ?>
<div class="container">
    <br><br><br>
    <div class="row">
    <h1>¿Está seguro de ELIMINAR la explotación?</h1>
    </div>
    <br>
    <div class="row">
        <form action="<?php echo base_url . "sadmin.php/?controller=Explotacion&action=delete";?>" method="POST" class="col">
            <div class="form-group">
                <label for="id">ID</label>
                <input class="form-control" type="text" name="id_explotacion" id="id_explotacion" value ="<?php echo $id ;?>" readonly="" >
            </div>
            <div class="form-group">
                <label for="id">Municipio</label>
                <input class="form-control" type="text" name="municipio" id="municipio" value ="<?php echo $municipio ;?>" readonly="">
            </div>
            <br><br>
                    <button type="submit" class="btn btn-danger col-1">Eliminar</button>
                    <a href="<?php echo base_url."sadmin.php/?controller=explotacion&action=index" ?>" class="btn btn-secondary col-1">Cancelar</a>
        </form>
    </div>
</div>    
<?php  require_once 'views/layaout/footer.php';   ?>


