<?php
    
    require_once 'views/layaout/header.php';
 ?>
<div class="container">
    <br>
    <br>
    <br>
   
        <div class="row my-2">
            <div class="col">
                <table id="tablon" class=" table table-striped table-bordered table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>EXPLOTACION</th>
                            <th>OPCIONES</th>    
                        </tr>
                    </thead>
                    <br><br>
                    <tbody>
                        <?php foreach($datos as $dato){ ?>  
                        <tr>
                            <td>
                               <?php echo $dato['id_explotacion']; ?>
                            </td>
                             <td>
                               <?php echo $dato['municipio']; ?>
                            </td>
                             <td>
                                 <div class="row">
                                     <div class="col-6">
                                        <a href="<?php echo base_url."sadmin.php/?controller=explotacion&action=nuevoeditar&dato=".$dato['id_explotacion'] ?>" class="btn btn-warning btn-block">Editar</a>
                                    </div>
                                    <div class="col-6">  
                                        <button class="btn btn-danger btn-block" id="<?php echo $dato['id_explotacion'];?>">Eliminar</button>
                                        <?php /*
                                        <!--<a id="<?php echo $dato['id_explotacion'];?>" href="<?php echo base_url."sadmin.php/?controller=explotacion&action=eliminar&dato=".$dato['id_explotacion'] ?>" class="btn btn-danger btn-block">Eliminar</a>-->
                                         * */?>
                                    </div>
                                 </div>
                            </td>
                        </tr>
                              
                           <?php }  ?>
                        
                    </tbody>
                    
                </table>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <a href="<?php echo base_url."sadmin.php/?controller=explotacion&action=nuevo" ?>" class="btn btn-success">Añadir</a>
            </div>
        </div>
</div>

<br>
<br>
<br>
<button class="btn btn-default" id="btn-confirm">Confirm</button>

<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="mi-modal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="myModalLabel">Eeliminar el elemento?<span id="ref"></span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
            Si acepta se borrara el elemento definitivamente.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="modal-btn-si">Si</button>
        <button type="button" class="btn btn-primary" id="modal-btn-no">No</button>
      </div>
    </div>
  </div>
</div>
<div class="alert" role="alert" id="result"></div>
  	

<!--<tr><td> $dato['id']</td><td>$dato['municipio']</td><td>[editar][borrar]</td></tr>-->

 <!-- datatables -->
<link rel="stylesheet" type="text/css" href="../assets/css/dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="../assets/css/dataTables.bootstrap4.min.css"/>
<script type="text/javascript" src="../assets/js/dataTables.min.js"></script> 
<script type="text/javascript" src="../assets/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="../assets/js/modal.js"></script>
    
<?php
    require_once 'views/layaout/footer.php';
 ?>
