<?php
    
    require_once 'views/layaout/header.php';
 ?>
<div class="container">
    <br>
    <br>
    <br>
   
        <div class="row my-2">
            <div class="col">
                <table id="tablon" class=" table table-striped table-bordered table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>EXPLOTACION</th>
                            <th>OPCIONES</th>    
                        </tr>
                    </thead>
                    <br><br>
                    <tbody>
                        <?php foreach($datos as $dato){ ?>  
                        <tr>
                            <td>
                               <?php echo $dato['id_explotacion']; ?>
                            </td>
                             <td>
                               <?php echo $dato['municipio']; ?>
                            </td>
                             <td>
                               [editar][borrar]
                            </td>
                        </tr>
                              
                           <?php }  ?>
                        
                    </tbody>
                    
                </table>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <a href="<?php echo base_url."sadmin.php?controller=Explotacion&action=add" ?>" class="btn btn-success">Añadir</a>
            </div>
        </div>
</div>
     

  	

<!--<tr><td> $dato['id']</td><td>$dato['municipio']</td><td>[editar][borrar]</td></tr>-->

 <!-- datatables -->
 <link rel="stylesheet" type="text/css" href="../assets/css/dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="../assets/css/dataTables.bootstrap4.min.css"/>
<script type="text/javascript" src="../assets/js/dataTables.min.js"></script> 
<script type="text/javascript" src="../assets/js/dataTables.bootstrap4.min.js"></script>

<?php

    require_once 'views/layaout/footer.php';
    
    

 ?>
