<?php
     $menu = [
      "inicio"        =>  "",
      "explotaciones" =>  "active",
      "acceso"        =>  "",
      "registro"      =>  ""
    ];
    $menu2 = [
      "explotaciones" =>  "active",
      "instalaciones" =>  "",
      "operarios"     =>  ""
    ];
     require_once 'views/layaout/header.php';
     require_once 'views/layaout/nav.php';

     $botonEditar = ($_SESSION['rol']=='admin')? "btn-secondary disabled" : "btn-warning";
     $botonEliminar = ($_SESSION['rol']=='admin')? "btn-secondary disabled" : "btn-danger";
 ?>


<div class="container">
 

    <br><br><br>  
        <h1>Listado de Explotaciones.</h1> 
        <div class="row my-2">
            <div class="col">
                <table id="tablon" class=" table table-striped table-bordered table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>EXPLOTACION</th>
                            <th>OPCIONES</th>    
                        </tr>
                    </thead>
                    <br><br>
                    <tbody>
                        <?php foreach($datos as $dato){   ?>  
                        
                        <tr> 
                            <td>
                               <?php echo $dato['id_explotacion']; ?>
                            </td>
                             <td>
                               <?php echo $dato['municipio']; ?>
                            </td>
                             <td>
                                 <div class="row">
                                     <div class="col-6">
                                        <a href="<?php echo base_url."sadmin.php/?controller=explotacion&action=nuevoeditar&dato=".$dato['id_explotacion'] ?>" class="btn btn-block <?php echo $botonEditar;?>">Editar</a>
                                    </div>
                                    <div class="col-6">  
                                      <a id="<?php echo $dato['id_explotacion'];?>" href="<?php echo base_url."sadmin.php/?controller=explotacion&action=eliminar&dato=".$dato['id_explotacion'] ?>" class="btn  btn-block <?php echo $botonEliminar;?>">Eliminar</a>
                                    </div>
                                 </div>
                            </td>
                        </tr>
                              
                           <?php }  ?>
                        
                    </tbody>
                    
                </table>
            </div>
        </div>
        <br>
        <div class="row mt-3">
            <div class="col">
              <?php if ($_SESSION['rol']=='superAdmin') { ?>
                <a href="<?php echo base_url."sadmin.php/?controller=explotacion&action=nuevo" ?>" class="btn btn-success">Añadir</a>
              <?php } ?>
            </div>
        </div>
</div>

<br>
<br>
<br>

 <!-- datatables -->
<link rel="stylesheet" type="text/css" href="../assets/css/dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="../assets/css/dataTables.bootstrap4.min.css"/>
<script type="text/javascript" src="../assets/js/dataTables.min.js"></script> 
<script type="text/javascript" src="../assets/js/dataTables.bootstrap4.min.js"></script>
   
<?php
    require_once 'views/layaout/footer.php';
 ?>
