<?php
  //index registro-----------------------------------------------------------------
     $menu = [
      "inicio"        =>  "",
      "explotaciones" =>  "",
      "acceso"        =>  "",
      "registro"      =>  "active"
    ];
       require_once 'views/layaout/header.php';
 ?>
<div class="container">
  <br><br><br>

  <div class="row"> 
      <h1> Control de accesos.</h1>
  </div>  
    <br>
        
          <form action="" class="form" method="POST">
            <div class="form-row align-items-end">
               <div class="col-4">
                   <label for=" finicio"> Fecha inicio</label>
                    <input type="date" class="form-control" name="finicio" id="finicio">
                </div>
                <div class="col-4">
                     <label for=" ffin"> Fecha fin</label>
                     <input type="date" class="form-control" name="ffin" id="ffin">
                </div>
                <div class="col-4">
                     <input type="submit" class="btn btn-primary btn-block mb-1" name="Filrar" id="Filtrar">
                </div>
            </div>
          </form>
        
        <div class="row my-2">
            <div class="col">
                <table id="tablon" class=" table table-striped table-bordered table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th>FECHA</th>   
                            <th>H.INICIO</th>
                            <th>H.FIN</th>
                            <th>NOMBRE</th>
                            <th>INSTALACION</th>
                            <th>EXPLOTACION</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <br><br>
                    <tbody>
                        <?php foreach($datos as $dato){ ?>  
                        <tr>
                             <td>
                               <?php echo $dato['fecha']; ?>
                            </td>
                            <td>
                               <?php echo $dato['hora_inicio']; ?>
                            </td>
                            <td>
                               <?php echo $dato['hora_fin']; ?>
                            </td>
                            <td>
                               <?php echo $dato['nombre_visita']; ?>
                            </td>
                            <td>
                               <?php echo $dato['id_instalacion2']; ?>
                            </td>
                            <td>
                               <?php echo $dato['id_explotacion3']; ?>
                            </td>
                            
                             <td>
                                 <div class="row">
                                     <div class="col-12">
                                        <a href="<?php echo base_url."sadmin.php/?controller=Registro&action=ver&dato=".$dato['id_registro'] ?>" class="btn btn-primary btn-block">Ver</a>
                                    </div> 
                                  </div>
                                 </div>
                            </td>
                        </tr>
                              
                           <?php }  ?>
                        
                    </tbody>
                    
                </table>
            </div>
        </div>
        <br>
        <div class="row mt-3">
            <div class="col">
                <a href="<?php echo base_url."sadmin.php/?controller=Acceso&action=nuevo" ?>" class="btn btn-success">Añadir</a>
            </div>
        </div>
</div>

<br>
<br>
<br>

 <!-- datatables -->
<link rel="stylesheet" type="text/css" href="../assets/css/dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="../assets/css/dataTables.bootstrap4.min.css"/>
<script type="text/javascript" src="../assets/js/dataTables.min.js"></script> 
<script type="text/javascript" src="../assets/js/dataTables.bootstrap4.min.js"></script>
   
<?php
    require_once 'views/layaout/footer.php';
 ?>
