<?php
    //nuevo.phtml -- acceso

    $menu = [
      "inicio"        =>  "",
      "explotaciones" =>  "",
      "acceso"        =>  "",
      "registro"      =>  "registro"
    ];

    include 'views/layaout/header.php';
 ?>

 <div class="container">
    <br><br><br>
    <div class="row">
    <h1> Ver registro</h1>
    </div>
    <br>
    <div class="row">
        <form action="<?php echo base_url . "sadmin.php/?controller=Acceso&action=index" ?>" method="POST" class="col needs-validation">
            <div class="form-row ">
               <div class="form-group col">
                    <label for="">Fecha</label>
                   <input class="form-control" type="text" value = "<?php echo $datos['fecha'] ?>">
               </div>
            <div class="form-group col">
                                <label for="">Hora Inicio</label>
                                <input class="form-control" type="text" value = "<?php echo $datos['hora_inicio'] ?>">
            </div>
                <div class="form-group col">
                    <label for="">Hora Fin</label>
                    <input class="form-control" type="text" value = "<?php echo $datos['hora_fin'] ?>">
                </div>
            </div>

            <div class="form-row ">
               <div class="form-group col">
                    <label for="">Explotacion</label>
                   <input class="form-control" type="text" value = "<?php echo $datos['id_explotacion3'] ?>">
               </div>
            <div class="form-group col">
                    <label for="">Instalacion</label>
                    <input class="form-control" type="text" value = "<?php echo $datos['id_instalacion2'] ?>">
            </div>
                <div class="form-group col">
                    <label for="">Operario</label>
                    <input class="form-control" type="text" value = "<?php echo $datos['id_usuario'] ?>">
                </div>
            </div>
            <div class="form-row ">
               <div class="form-group col-3">
                    <label for="">Nombre Visita</label>
                   <input class="form-control" type="text" value = "<?php echo $datos['nombre_visita'] ?>">
               </div>
            <div class="form-group col-2">
                    <label for="">DNI</label>
                    <input class="form-control" type="text" value = "<?php echo $datos['dni_visita'] ?>">
            </div>
                <div class="form-group col-7">
                    <label for="">Observaciones</label>
                    <input class="form-control" type="text" value = "<?php echo $datos['observaciones'] ?>">
                </div>
            </div>
           
            <br>
            <div class="form-row">
                <div class="col-2"></div>
                <div class="col-4">
                    <div class="form-check  ">
                        <input class="form-check-input" type="checkbox" id="inlineCheckbox1"
                        <?php if ($datos['condiciones']){ echo "checked";}; ?>>
                         <label class="form-check-label" for="inlineCheckbox1">Acepta Condiciones y LPDG </label>
                    </div>
                </div>
                 <div class="col-2"></div>
                <div class="col-4">
                    <div class="form-check ">
                         <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2"
                         <?php if ($datos['prl']){ echo "checked";}; ?>>
                         <label class="form-check-label" for="inlineCheckbox2">Acepta PRL</label>
                    </div>
                </div>
               
            </div>
            <br>
            <div class="form-group ">
                    <label for="">Firma</label>
                    <input class="form-control" type="text" value = "<?php echo $datos['firma'] ?>">
            </div>
                <!-- <button type="submit" class="btn btn-success col-1"><?php echo $_GET['action'] ?></button> -->
                <a href="<?php echo base_url."sadmin.php/?controller=Registro&action=index" ?>" class="btn btn-secondary col-1">Volver</a>
           
        </form>
    </div>
</div>    




<?php  require_once 'views/layaout/footer.php';   ?>
