<?php
     $menu = [
      "inicio"        =>  "",
      "explotaciones" =>  "active",
      "acceso"        =>  "",
      "registro"      =>  ""
    ];
     $menu2 = [
      "explotaciones" =>  "",
      "instalaciones" =>  "",
      "operarios"     =>  "active"
    ];
    //var_dump($datos);
     require_once 'views/layaout/header.php';
     require_once 'views/layaout/nav.php';
 ?>


<div class="container">
 

    <br><br><br>   
    <h1>Listado de Operarios.</h1>
        <div class="row my-2">
            <div class="col">
                <table id="tablon" class=" table table-striped table-bordered table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>EXPLOTACION</th>  
                            <th>NOMBRE</th> 
                            <th>OPCIONES</th> 
                        </tr>
                    </thead>
                    <br><br>
                    <tbody>
                        <?php foreach($datos as $dato){ ?>  
                        <tr>
                            <td>
                               <?php echo $dato['id_usuario']."\n"; ?>
                            </td>
                             <td>
                               <?php echo $dato['id_explotacion2']."\n"; ?>
                            </td>
                             <td>
                               <?php echo $dato['nombre']."\n"; ?>
                            </td>
                             <td>
                                 <div class="row">
                                     <div class="col-6">
                                        <a href="<?php echo base_url."sadmin.php/?controller=Usuario&action=editar&dato=".$dato['id_usuario'] ?>" class="btn btn-warning btn-block">Editar</a>
                                    </div>
                                    <div class="col-6">  
                                      <a id="<?php echo $dato['id_usuario'];?>" href="<?php echo base_url."sadmin.php/?controller=Usuario&action=eliminar&dato=".$dato['id_usuario'] ?>" class="btn btn-danger btn-block">Eliminar</a>
                                    </div>
                                 </div>
                            </td>
                        </tr>
                              
                           <?php }  ?>
                        
                    </tbody>
                    
                </table>
            </div>
        </div>
        <br>
        <div class="row mt-3">
            <div class="col">
                <a href="<?php echo base_url."sadmin.php/?controller=Usuario&action=nuevo" ?>" class="btn btn-success">Añadir</a>
            </div>
        </div>
</div>

<br>
<br>
<br>

 <!-- datatables -->
<link rel="stylesheet" type="text/css" href="../assets/css/dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="../assets/css/dataTables.bootstrap4.min.css"/>
<script type="text/javascript" src="../assets/js/dataTables.min.js"></script> 
<script type="text/javascript" src="../assets/js/dataTables.bootstrap4.min.js"></script>
   
<?php
    require_once 'views/layaout/footer.php';
 ?>
